namespace: main

app:
  replicaCount: 2
  name: diplo-app

  image: ghcr.io/lozovoya/diplo-app
  tag: 35a7899373a64053b997a2fdf34ee4a565716fa9

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  appPort: 80

