name: "Deploy"

on:
#  push:
#    branches:
#    - main
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    #name: "Build image"
    runs-on: self-hosted
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Login to k8s cluster
      run: ssh -i ${{ secrets.SSH_KEY }} debian@${{ variables.KUBE_MASTER_IP }}

    - name: Deploy
      run: |-
