name: "Deploy to kuber"

on:
  push:
    tags:
    - v1.*
    branches:
    - develop
#  pull_request:
#    branches: [ "main" ]

env:
  IMAGE_ID: ghcr.io/${{ github.repository_owner }}/diplo-app

jobs:
  buildandpush:
    uses: lozovoya/diplo2/.github/workflows/diplo-app-buildandpush.yaml@develop
    secrets: inherit
  deploy:
    needs: buildandpush
    runs-on: self-hosted
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Copy private key from environment variable to file
      run: |-
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy
      run: |
        ssh -i ~/.ssh/id_rsa debian@${{ vars.KUBE_MASTER_IP }} \
        "kubectl set image deploy/diplo-app --namespace=${GITHUB_REF_NAME} diplo-app=$IMAGE_ID-${GITHUB_REF_NAME}:${GITHUB_SHA} && \
        kubectl rollout restart deploy diplo-app --namespace=${GITHUB_REF_NAME}"





