name: "Build and push image, deploy to kuber"

on:
  workflow_call:

#    branches:
#    - develop
#  pull_request:
#    branches: [ "main" ]

env:
  BRANCH: develop
  IMAGE_ID: ghcr.io/${{ github.repository_owner }}/diplo-app

jobs:
  build:
    #name: "Build image"
    runs-on: self-hosted
    defaults:
      run:
        shell: bash

    steps:

    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Build the Docker image
      run: |-
        docker build . --file Dockerfile --tag  $IMAGE_ID-${GITHUB_REF_NAME}:${GITHUB_SHA} --tag  $IMAGE_ID-${GITHUB_REF_NAME}:latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Push image
      run: |-
        export IMAGE_ID=ghcr.io/${{ github.repository_owner }}/diplo-app-${GITHUB_REF_NAME}
        echo $IMAGE_ID
        docker image push --all-tags $IMAGE_ID-${GITHUB_REF_NAME}





