name: "Build and push image"

on:
  push:
    branches:
    - main
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    #name: "Build image"
    runs-on: self-hosted
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag  ghcr.io/${{ github.repository_owner }}/diplo-app:${GITHUB_SHA}
      run: docker build . --file Dockerfile --tag  ghcr.io/${{ github.repository_owner }}/diplo-app:latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image
      run: docker push ghcr.io/${{ github.repository_owner }}/diplo-app:latest

#    - name: Build and push Docker image
#      uses: docker/build-push-action@v3
#      with:
#        push: true
#        tags: |
#          ${{ github.repository_owner }}/diplo-app:latest
#          ${{ github.repository_owner }}/diplo-app:${{ github.sha }}
#        cache-from: type=gha
#        cache-to: type=gha,mode=max




